### ISSUE TITLE
Panic at topK sort LLAMA

### ISSUE THREAD

**Issue by rickbeeloo** [EricLBuehler/mistral.rs#777]
First of all, thanks for for building this @EricLBuehler!

## Describe the bug
When running `./target/release/mistralrs-server -i plain -m meta-llama/Meta-Llama-3.1-8B-Instruct -a llama ` I get the following trace:

I get:

```
IuDakitynclonатковμοί …ickerViewernetARRIER$)/buttons10&%/Hthread '<unnamed>' panicked at mistralrs-core/src/sampler.rs:416:72:
No ordering.

```
Full output:

```
./target/release/mistralrs-server -i plain -m meta-llama/Meta-Llama-3.1-8B-Instruct -a llama 
2024-09-15T07:21:46.039337Z  INFO mistralrs_server: avx: true, neon: false, simd128: false, f16c: true
2024-09-15T07:21:46.039366Z  INFO mistralrs_server: Sampling method: penalties -> temperature -> topk -> topp -> minp -> multinomial
2024-09-15T07:21:46.039369Z  INFO mistralrs_server: Using flash attention.
2024-09-15T07:21:46.039378Z  INFO mistralrs_server: Model kind is: normal (no quant, no adapters)
2024-09-15T07:21:46.047192Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer.json` at `meta-llama/Meta-Llama-3.1-8B-Instruct`
2024-09-15T07:21:46.059368Z  INFO mistralrs_core::pipeline::normal: Loading `config.json` at `meta-llama/Meta-Llama-3.1-8B-Instruct`
2024-09-15T07:21:46.212044Z  INFO mistralrs_core::pipeline::paths: Found model weight filenames ["model-00001-of-00004.safetensors", "model-00002-of-00004.safetensors", "model-00003-of-00004.safetensors", "model-00004-of-00004.safetensors"]
2024-09-15T07:21:46.335644Z  INFO mistralrs_core::pipeline::normal: Loading `generation_config.json` at `meta-llama/Meta-Llama-3.1-8B-Instruct`
2024-09-15T07:21:46.552648Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer_config.json` at `meta-llama/Meta-Llama-3.1-8B-Instruct`
2024-09-15T07:21:46.559680Z  INFO mistralrs_core::pipeline::normal: Loading model `meta-llama/Meta-Llama-3.1-8B-Instruct` on cuda[0].
2024-09-15T07:21:46.596906Z  INFO mistralrs_core::utils::normal: Detected minimum CUDA compute capability 8.6
2024-09-15T07:21:46.741052Z  INFO mistralrs_core::utils::normal: DType selected is BF16.
2024-09-15T07:21:46.741090Z  INFO mistralrs_core::pipeline::normal: Model config: Config { hidden_size: 4096, intermediate_size: 14336, vocab_size: 128256, num_hidden_layers: 32, num_attention_heads: 32, num_key_value_heads: 8, use_flash_attn: true, rms_norm_eps: 1e-5, rope_theta: 500000.0, max_position_embeddings: 131072, rope_scaling: Some(Llama3RopeConfig { factor: 8.0, low_freq_factor: 1.0, high_freq_factor: 4.0, original_max_position_embeddings: 8192, rope_type: Llama3 }), quantization_config: None }
100%|█████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 4.92it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 82/82 [00:04<00:00, 12.11it/s]
100%|████████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 24.61it/s]
100%|████████████████████████████████████████████████████████████████████████████| 104/104 [00:04<00:00, 68.65it/s]
2024-09-15T07:21:52.437893Z  INFO mistralrs_core::paged_attention: Allocating 27015 MB for PagedAttention KV cache
2024-09-15T07:21:52.437913Z  INFO mistralrs_core::paged_attention: Using PagedAttention with block size 32 and 6753 GPU blocks: available context length is 216096 tokens
2024-09-15T07:21:52.791270Z  INFO mistralrs_core::pipeline::chat_template: bos_toks = "<|begin_of_text|>", eos_toks = "<|eot_id|>", "<|end_of_text|>", "<|eom_id|>", unk_tok = `None`
2024-09-15T07:21:52.831751Z  INFO mistralrs_server: Model loaded.
2024-09-15T07:21:52.832411Z  INFO mistralrs_core: Enabling GEMM reduced precision in BF16.
2024-09-15T07:21:52.865786Z  INFO mistralrs_core: Enabling GEMM reduced precision in F16.
2024-09-15T07:21:52.866774Z  INFO mistralrs_core::cublaslt: Initialized cuBLASlt handle
2024-09-15T07:21:52.866862Z  INFO mistralrs_server::interactive_mode: Starting interactive loop with sampling params: SamplingParams { temperature: Some(0.1), top_k: Some(32), top_p: Some(0.1), min_p: Some(0.05), top_n_logprobs: 0, frequency_penalty: Some(0.1), presence_penalty: Some(0.1), stop_toks: None, max_len: Some(4096), logits_bias: None, n_choices: 1, dry_params: Some(DrySamplingParams { sequence_breakers: ["\n", ":", "\"", "*"], multiplier: 0.0, base: 1.75, allowed_length: 2 }) }
> hello sir
IuDakitynclonатковμοί …ickerViewernetARRIER$)/buttons10&%/Hthread '<unnamed>' panicked at mistralrs-core/src/sampler.rs:416:72:
No ordering.
```

## Latest commit or version
version: a702c6dd2944aaf75800b11f4dfeec6fe5a9b068

At least the "IuDakitynclonатковμοί …ickerViewernetARRIER$" made me laugh :)

**Comment by EricLBuehler** [comment]
Hi @rickbeeloo! It seems the issue relates to flash attention, as otherwise it works. I'll take a look!

**Comment by rickbeeloo** [comment]
@EricLBuehler thanks! And for the quick reply :)

**Comment by EricLBuehler** [comment]
@rickbeeloo can you please share the build command you used?

**Comment by rickbeeloo** [comment]
@EricLBuehler currently outside, but I had some trouble so followed the other issues (using cuda 12.6) and had to add “fIPC” flag. Will check in a bit the exact command

**Comment by rickbeeloo** [comment]
@EricLBuehler, the command I used:

```
CUDA_NVCC_FLAGS=-fPIC cargo build  --release --features "cuda flash-attn" 
```

I just checked the `probs` vector and there are indeed `NaN`s in it. 

The others:

❌ **cuda**
```
cargo build  --release --features cuda
```
Linking error:

```
error: could not compile `mistralrs-bench` (bin "mistralrs-bench") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `mistralrs-pyo3` (lib) due to 1 previous error
error: linking with `cc` failed: exit status: 1
```

❌ **cuda fPIC**
```
CUDA_NVCC_FLAGS=-fPIC cargo build  --release --features cuda
```
Linking error:

```
error: could not compile `mistralrs-pyo3` (lib) due to 1 previous error
error: linking with `cc` failed: exit status: 1
```

✅ **cuda flasth-attn**
```
cargo build  --release --features "cuda flash-attn"
```
This works, but:

```
probs: valid numbers..., NaN, NaN, NaN...NaN]
```
With the error:
```
thread '<unnamed>' panicked at mistralrs-core/src/sampler.rs:419:72:
No ordering
```

✅ **cuda flasth-attn fPIC**

```
CUDA_NVCC_FLAGS=-fPIC cargo build  --release --features "cuda flash-attn" 
```
This works, but

```
probs: valid numbers..., NaN, NaN, NaN...NaN]
```
With the error:
```
thread '<unnamed>' panicked at mistralrs-core/src/sampler.rs:419:72:
No ordering
```

**More system info**
Some more system info:

**Cuda**
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:10:22_PDT_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0
```

**Python**
I had to upgrade this for PyO3:
```
Python 3.12.5
```

**Rust**
Tried nightly:
```
rustc 1.83.0-nightly (4ac7bcbaa 2024-09-04)
```
and stable:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

**Ubuntu**
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

**GPU**
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A6000               Off |   00000000:17:00.0 Off |                  Off |
| 30%   33C    P8             22W /  300W |       2MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A6000               Off |   00000000:73:00.0 Off |                  Off |
| 30%   32C    P8             20W /  300W |       2MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Let me know :)**
Let me know what else I could try / if you need more info. 

Thanks!

**Comment by rickbeeloo** [comment]
I got this to work with Cuda 12.4 instead of 12.6, not really a "fix" but at least it works :)

**Comment by EricLBuehler** [comment]
@rickbeeloo strangely, my machine is CUDA 12.6 on WSL, and it works.
