### ISSUE TITLE
DiffusionArchitecture not found in python package 

### ISSUE THREAD

**Issue by Manojbhat09** [EricLBuehler/mistral.rs#943]
## Minimum reproducible example ## Error
```
(edge) root@C.13914965:/home/mbhat/mistral.rs/mistralrs-pyo3$ pip install mistralrs -v --upgrade
Using pip 24.2 from /home/mbhat/miniconda/envs/edge/lib/python3.10/site-packages/pip (python 3.10)
Collecting mistralrs
  Obtaining dependency information for mistralrs from https://files.pythonhosted.org/packages/0e/4b/849e71d4f3f061fca807b5aa255022eec160acdab10a47b4595a8a68c5ec/mistralrs-0.3.2-cp310-cp310-manylinux_2_34_x86_64.whl.metadata
  Downloading mistralrs-0.3.2-cp310-cp310-manylinux_2_34_x86_64.whl.metadata (1.7 kB)
Downloading mistralrs-0.3.2-cp310-cp310-manylinux_2_34_x86_64.whl (14.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.4/14.4 MB 6.4 MB/s eta 0:00:00
Installing collected packages: mistralrs
Successfully installed mistralrs-0.3.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
(edge) root@C.13914965:/home/mbhat/mistral.rs/mistralrs-pyo3$ python
Python 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mistralrs import DiffusionArchitecture
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DiffusionArchitecture' from 'mistralrs' (/home/mbhat/miniconda/envs/edge/lib/python3.10/site-packages/mistralrs/__init__.py)
```

## Other information
Ubuntu 22
```
(edge) root@C.13914965:/home/{}/mistral.rs/mistralrs-pyo3$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

## Latest commit or version
[680874d](https://github.com/EricLBuehler/mistral.rs/commit/680874d41d6f14735c5917b44ab83f0173d66e80)

**Comment by Manojbhat09** [comment]
was it also updated on pypi? 

```
root@C.13914965:/home/{}$ pip index versions mistralrs
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
mistralrs (0.3.2)
Available versions: 0.3.2, 0.3.1, 0.3.0, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.24, 0.1.23, 0.1.22, 0.1.21, 0.1.20, 0.1.19, 0.1.18, 0.1.17, 0.1.16, 0.1.15, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10, 0.1.8, 0.1.7, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
  INSTALLED: 0.3.2
  LATEST:    0.3.2
root@C.13914965:/home/{}$ pip cache purge
Files removed: 253
root@C.13914965:/home/{}$ pip cache remove mistralrs
WARNING: No matching packages for pattern "mistralrs"
Files removed: 0
root@C.13914965:/home/{}$ pip install mistralrs==0.3.4 --no-cache-dir
ERROR: Could not find a version that satisfies the requirement mistralrs==0.3.4 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2)
ERROR: No matching distribution found for mistralrs==0.3.4
root@C.13914965:/home/{}$ pip install --upgrade pip
Requirement already satisfied: pip in ./miniconda/envs/edge/lib/python3.10/site-packages (24.2)
Collecting pip
  Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 14.8 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-24.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@C.13914965:/home/{}$ pip install mistralrs==0.3.4 --no-cache-dir
ERROR: Could not find a version that satisfies the requirement mistralrs==0.3.4 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2)
ERROR: No matching distribution found for mistralrs==0.3.4
```

**Comment by EricLBuehler** [comment]
@Manojbhat09 yes. What is your system information (aarch64/x64, OS, Python version)?

**Comment by Manojbhat09** [comment]
here:

```
root@85fb11c19678:/workspace# python flux.py 
Traceback (most recent call last):
  File "/workspace/flux.py", line 1, in <module>
    from mistralrs import (
ImportError: cannot import name 'DiffusionArchitecture' from 'mistralrs' (/usr/local/lib/python3.10/dist-packages/mistralrs/__init__.py)
root@85fb11c19678:/workspace# which python
/usr/bin/python
root@85fb11c19678:/workspace# python
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@85fb11c19678:/workspace# lsb-release -a
bash: lsb-release: command not found
root@85fb11c19678:/workspace# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

could you please recheck 


```

root@85fb11c19678:/workspace# pip install mistralrs==0.3.4
ERROR: Could not find a version that satisfies the requirement mistralrs==0.3.4 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2)
ERROR: No matching distribution found for mistralrs==0.3.4

```

**Comment by EricLBuehler** [comment]
@Manojbhat09 this is very interesting. In the meantime, are you able to install `mistralrs` from source?
