### ISSUE TITLE
is_streaming: true gives unreachable code panic

### ISSUE THREAD

**Issue by dancixx** [EricLBuehler/mistral.rs#953]
Using `is_streaming: true` in the `Reques::Normal(NormalRequest {...})` struct is causing panic.
Using `is_streaming: false` runs without any bugs, but if it is `true`, I get panicked.

Maybe I am doing wrong and missed something, but I couldn't find any example where the `is_streaming: true` is used.

This is my example:
```rust
  pub async fn token_stream(&self, messages: IntstructModelInput) -> Result<(), Error> {
    messages.validate()?;

    let model = self.build().await?;
    let (tx, mut rx) = channel(10_000);
    let msg = Request::Normal(NormalRequest {
      messages: RequestMessage::Chat(messages.into()),
      sampling_params: SamplingParams::deterministic(),
      response: tx,
      return_logprobs: false,
      is_streaming: false,
      id: 0,
      constraint: Constraint::None,
      suffix: None,
      adapters: None,
      tools: None,
      tool_choice: None,
      logits_processors: None,
    });

    tokio::task::spawn_blocking(move || {
      model.get_sender().unwrap().blocking_send(msg).unwrap();
    });

    let stream = rx.recv().await.unwrap().as_result()?;
    match stream {
      ResponseOk::Done(c) => println!(
        "Text: {}, Prompt T/s: {}, Completion T/s: {}",
        c.choices[0].message.content.as_ref().unwrap(),
        c.usage.avg_prompt_tok_per_sec,
        c.usage.avg_compl_tok_per_sec
      ),
      _ => unreachable!(),
    }

    Ok(())
  }
  
  // test function
  #[tokio::test(flavor = "multi_thread")]
  #[traced_test]
  async fn gemma1_1_2b_it() -> Result<(), anyhow::Error> {
    let model = TextModel::new(Model::Gemma1_1_2BIt);
    model
      .token_stream(IntstructModelInput::Gemma(vec![
        (TextMessageRole::User, "Hello".to_string()),
        (TextMessageRole::Assistant, "Hi".to_string()),
        (TextMessageRole::User, "How are you?".to_string()),
        (TextMessageRole::Assistant, "I'm fine, thank you.".to_string()),
      ]))
      .await?;

    Ok(())
  }
```

The backtrace:
```
thread 'model::tests::gemma1_1_2b_it' panicked at engine/src/model.rs:118:12:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bc5cf994db9fb46712cefd89f78ad7fc51f184a2/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/bc5cf994db9fb46712cefd89f78ad7fc51f184a2/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/bc5cf994db9fb46712cefd89f78ad7fc51f184a2/library/core/src/panicking.rs:152:5
   3: engine::model::TextModel::token_stream::{{closure}}
             at ./src/model.rs:118:12
   4: engine::model::tests::gemma1_1_2b_it::{{closure}}
             at ./src/model.rs:217:8
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/danixx/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:123:9
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:63
   7: tokio::runtime::coop::with_budget
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/coop.rs:73:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/park.rs:281:31
  10: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/blocking.rs:66:9
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  12: tokio::runtime::context::runtime::enter_runtime
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/context/runtime.rs:65:16
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  14: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:370:45
  15: tokio::runtime::runtime::Runtime::block_on
             at /Users/danixx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.41.1/src/runtime/runtime.rs:342:13
  16: engine::model::tests::gemma1_1_2b_it
             at ./src/model.rs:219:5
  17: engine::model::tests::gemma1_1_2b_it::{{closure}}
             at ./src/model.rs:208:32
  18: core::ops::function::FnOnce::call_once
             at /Users/danixx/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/bc5cf994db9fb46712cefd89f78ad7fc51f184a2/library/core/src/ops/function.rs:250:5
```

**Comment by dancixx** [comment]
That was my mistake. I am closing this issue.
